### ISSUE TITLE
Het lang element klopt niet helemaal lijkt het

### ISSUE THREAD

**Issue by Tindyy** [RukiyaTossou/the-startup-responsive-interactieve-website#1]
https://github.com/RukiyaTossou/the-startup-responsive-interactieve-website/blob/52810571cd68ab3be82587909da6f7e0ebce4242/index.html#L1

Het lang staat ingesteld op "nl" terwijl de rest van de code bijna helemaal in het engels staat.

**Comment by Tindyy** [comment]
Oh JK uhm ik denk dat ik me beter kan inlezen op lang element lol.

**Comment by RukiyaTossou** [comment]
XD
