### ISSUE TITLE
Let op spaties tussen attributen 

### ISSUE THREAD

**Issue by EBok1** [RukiyaTossou/the-startup-responsive-interactieve-website#6]
https://github.com/RukiyaTossou/the-startup-responsive-interactieve-website/blob/52810571cd68ab3be82587909da6f7e0ebce4242/index.html#L97

spatie tussen: img" src"

**Comment by RukiyaTossou** [comment]
```<img  class="art-img" src="./docs/images/layla_art.jpeg" alt="layla-img-art">```
Gefixt!
